version: '3.6'
services:
  web:
    container_name: commun_web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - $DOCKER_CONNECTOR_WEB_HOST:$DOCKER_CONNECTOR_WEB_PORT:$DOCKER_CONNECTOR_WEB_PORT
    env_file:
      - .env
