version: '3.6'
services:
  commun-web:
    container_name: commun-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BRANCH_NAME: $BUILDKITE_BRANCH
        COMMIT_HASH: $BUILDKITE_COMMIT

    ports:
      - $DOCKER_CONNECTOR_WEB_HOST:$DOCKER_CONNECTOR_WEB_PORT:$DOCKER_CONNECTOR_WEB_PORT
    env_file:
      - .env
