export const OAUTH_SCREEN_ID = 'OAUTH_SCREEN_ID';
export const REGISTERED_SCREEN_ID = 'REGISTERED_SCREEN_ID';
export const PHONE_SCREEN_ID = 'PNONE_SCREEN_ID';
export const CONFIRM_CODE_SCREEN_ID = 'CONFIRM_CODE_SCREEN_ID';
export const CREATE_USERNAME_SCREEN_ID = 'CREATE_USERNAME_SCREEN_ID';
export const CREATE_PASSWORD_SCREEN_ID = 'CREATE_PASSWORD_SCREEN_ID';
export const CONFIRM_PASSWORD_SCREEN_ID = 'CONFIRM_PASSWORD_SCREEN_ID';
export const MASTER_KEY_SCREEN_ID = 'MASTER_KEY_SCREEN_ID';
