steps:

  - label: ":docker: build dev image"
    command: ".buildkite/steps/build.sh"
    id: commun-vault-1

  - wait

  - trigger: "deploy-front dev"
    label: ":partyparrot: dev.commun.com"
    build:
      message: ":rocket: ${BUILDKITE_TAG} to dev"
      env:
        BUILDKITE_CLEAN_CHECKOUT: "true"
        DEPLOY_TAG: "dev-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
        DEPLOY_ENV: "dev"
    if: build.branch == 'master' || (build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != "")
  
  - wait

  - trigger: "deploy-front dev-3"
    label: ":partyparrot: dev-3.commun.com"
    build:
      message: ":rocket: ${BUILDKITE_TAG} to dev-3"
      env:
        BUILDKITE_CLEAN_CHECKOUT: "true"
        DEPLOY_TAG: "dev-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
        DEPLOY_ENV: "dev-3"
    if: build.branch == 'dev-3'
  
  - wait

  - label: ":docker: release image with tag to docker hub"
    command: .buildkite/steps/release-image.sh
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""

  - wait

  - block: "Release?"
    prompt: "Release to https://commun.com?"
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""

  - wait

  - label: ":door: Concurrency gate"
    command: "exit 0"
    concurrency: 1
    concurrency_group: "deploy-concurrency-gate"

  - wait

  - trigger: "deploy-front"
    label: ":rocket: commun.com"
    build:
      message: ":rocket: ${BUILDKITE_TAG}"
      env:
        BUILDKITE_CLEAN_CHECKOUT: "true"
        DEPLOY_TAG: "${BUILDKITE_TAG}"
        DEPLOY_ENV: "prod"
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""
