steps:

  - label: ":docker: build dev image"
    command: ".buildkite/steps/build.sh"
    id: commun-vault-1

  - wait

  - label: ":partyparrot: dev.commun.com"
    command: "ansible-playbook -i .buildkite/hosts-commun-dev --vault-id hosts@~/commun-key -e \"deploy_type=dev deploy_tag=dev-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER deploy_port=3001\" .buildkite/playbooks/deploy.yaml --private-key ~/.ssh/id_ed25519"
    id: commun-vault-2
  
  - wait

  - block: "Release?"
    prompt: "Release to https://commun.com?"

  - wait

  - label: ":docker: release image to docker hub"
    command: .buildkite/steps/release-image.sh
   
  - wait

  - name: ":rocket: commun.com"
    command: "ansible-playbook -i .buildkite/hosts-commun --vault-id hosts@~/commun-key -e \"deploy_type=prod deploy_tag=$BUILDKITE_TAG deploy_port=3001\" .buildkite/playbooks/deploy.yaml --private-key ~/.ssh/id_ed25519"
    id: commun-vault-3        
