steps:

  - label: ":docker: build dev image"
    command: ".buildkite/steps/build.sh"
    id: commun-vault-1

  - wait

  - label: ":partyparrot: dev.commun.com"
    command: "ansible-playbook -i .buildkite/hosts-commun-dev --vault-id hosts@~/commun-key -e \"deploy_type=dev deploy_tag=dev-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER deploy_port=3000\" .buildkite/playbooks/deploy.yaml --private-key ~/.ssh/id_ed25519"
    if: build.branch == 'master' || (build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != "")
    id: commun-vault-2
  
  - wait

  - label: ":docker: release image with tag to docker hub"
    command: .buildkite/steps/release-image.sh
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""

  - wait

  - block: "Release?"
    prompt: "Release to https://commun.com?"
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""

  - wait

  - label: ":door: Concurrency gate"
    command: "exit 0"
    concurrency: 1
    concurrency_group: "deploy-concurrency-gate"

  - wait

  - trigger: "deploy-front"
    label: ":rocket: commun.com"
    build:
      message: ":rocket: ${BUILDKITE_TAG}"
      env:
        BUILDKITE_CLEAN_CHECKOUT: "true"
        DEPLOY_TAG: "${BUILDKITE_TAG}"
        DEPLOY_ENV: "prod"
    if: build.env("BUILDKITE_TAG") != null && build.env("BUILDKITE_TAG") != ""
