export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const VOTE_POST = 'VOTE_POST';
export const VOTE_POST_SUCCESS = 'VOTE_POST_SUCCESS';
export const VOTE_POST_ERROR = 'VOTE_POST_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const FETCH_FEED_COMMENTS = 'FETCH_FEED_COMMENTS';
export const FETCH_FEED_COMMENTS_SUCCESS = 'FETCH_FEED_COMMENTS_SUCCESS';
export const FETCH_FEED_COMMENTS_ERROR = 'FETCH_FEED_COMMENTS_ERROR';

export const DELETE_CONTENT = 'DELETE_CONTENT';
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS';
export const DELETE_CONTENT_ERROR = 'DELETE_CONTENT_ERROR';

export const UPDATE_UI_MODE = 'UPDATE_UI_MODE';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const GATE_AUTHORIZE_SECRET = 'GATE_AUTHORIZE_SECRET';
export const GATE_AUTHORIZE_SECRET_SUCCESS = 'GATE_AUTHORIZE_SECRET_SUCCESS';
export const GATE_AUTHORIZE_SECRET_ERROR = 'GATE_AUTHORIZE_SECRET_ERROR';

export const GATE_AUTHORIZE = 'GATE_AUTHORIZE';
export const GATE_AUTHORIZE_SUCCESS = 'GATE_AUTHORIZE_SUCCESS';
export const GATE_AUTHORIZE_ERROR = 'GATE_AUTHORIZE_ERROR';

export const SET_SERVER_ACCOUNT_NAME = 'SET_SERVER_ACCOUNT_NAME';

export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER';

export const PROVIDE_BW = 'PROVIDE_BW';
export const PROVIDE_BW_SUCCESS = 'PROVIDE_BW_SUCCESS';
export const PROVIDE_BW_ERROR = 'PROVIDE_BW_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

export const FETCH_EMBED = 'FETCH_EMBED';
export const FETCH_EMBED_SUCCESS = 'FETCH_EMBED_SUCCESS';
export const FETCH_EMBED_ERROR = 'FETCH_EMBED_ERROR';

/* for registration */
export const SET_SCREEN_ID = 'SET_SCREEN_ID';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_FULL_PHONE_NUMBER = 'SET_FULL_PHONE_NUMBER';
export const SET_LOC_DATA = 'SET_LOC_DATA';
export const SET_WISH_USERNAME = 'SET_WISH_USERNAME';
export const CLEAR_REGISTRATION_DATA = 'CLEAR_REGISTRATION_DATA';

/* export const FETCH_REG_STATE = 'FETCH_REG_STATE';
export const FETCH_REG_STATE_SUCCESS = 'FETCH_REG_STATE_SUCCESS';
export const FETCH_REG_STATE_ERROR = 'FETCH_REG_STATE_ERROR'; */

export const FETCH_REG_FIRST_STEP = 'FETCH_REG_FIRST_STEP';
export const FETCH_REG_FIRST_STEP_SUCCESS = 'FETCH_REG_FIRST_STEP_SUCCESS';
export const FETCH_REG_FIRST_STEP_ERROR = 'FETCH_REG_FIRST_STEP_ERROR';
export const SET_FIRST_STEP_ERROR = 'SET_FIRST_STEP_ERROR';
export const FIRST_STEP_STOP_LOADER = 'FIRST_STEP_STOP_LOADER';

export const FETCH_REG_VERIFY = 'FETCH_REG_VERIFY';
export const FETCH_REG_VERIFY_SUCCESS = 'FETCH_REG_VERIFY_SUCCESS';
export const FETCH_REG_VERIFY_ERROR = 'FETCH_REG_VERIFY_ERROR';
export const CLEAR_VERIFY_ERROR = 'CLEAR_VERIFY_ERROR';
export const CLEAR_REG_ERRORS = 'CLEAR_REG_ERRORS';
export const SET_LOCAL_STORAGE_DATA = 'SET_LOCAL_STORAGE_DATA';

export const FETCH_RESEND_SMS = 'FETCH_RESEND_SMS';
export const FETCH_RESEND_SMS_SUCCESS = 'FETCH_RESEND_SMS_SUCCESS';
export const FETCH_RESEND_SMS_ERROR = 'FETCH_RESEND_SMS_ERROR';

export const FETCH_REG_SET_USER = 'FETCH_REG_SET_USER';
export const FETCH_REG_SET_USER_SUCCESS = 'FETCH_REG_SET_USER_SUCCESS';
export const FETCH_REG_SET_USER_ERROR = 'FETCH_REG_SET_USER_ERROR';

export const START_REG_BLOCK_CHAIN = 'START_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN = 'FETCH_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN_SUCCESS = 'FETCH_REG_BLOCK_CHAIN_SUCCESS';
export const FETCH_REG_BLOCK_CHAIN_ERROR = 'FETCH_REG_BLOCK_CHAIN_ERROR';
export const BLOCK_CHAIN_STOP_LOADER = 'BLOCK_CHAIN_STOP_LOADER';
export const SET_USERS_KEYS = 'SET_USERS_KEYS';

/* for actions with users and communities  */
export const SET_POST_VOTE = 'SET_POST_VOTE';
export const SET_COMMENT_VOTE = 'SET_COMMENT_VOTE';

export const PIN = 'PIN';
export const PIN_SUCCESS = 'PIN_SUCCESS';
export const PIN_ERROR = 'PIN_ERROR';

export const UNPIN = 'UNPIN';
export const UNPIN_SUCCESS = 'UNPIN_SUCCESS';
export const UNPIN_ERROR = 'UNPIN_ERROR';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR';

export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_ERROR = 'UNBLOCK_USER_ERROR';

export const VOTE_LEADER = 'UNBLOCK_USER';
export const VOTE_LEADER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const VOTE_LEADER_ERROR = 'UNBLOCK_USER_ERROR';

export const UNVOTE_LEADER = 'UNBLOCK_USER';
export const UNVOTE_LEADER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNVOTE_LEADER_ERROR = 'UNBLOCK_USER_ERROR';

export const TRANSFER_TOKEN = 'TRANSFER_TOKEN';
export const TRANSFER_TOKEN_SUCCESS = 'TRANSFER_TOKEN_SUCCESS';
export const TRANSFER_TOKEN_ERROR = 'TRANSFER_TOKEN_ERROR';

export const FETCH_NOTIFICATIONS_COUNT = 'FETCH_NOTIFICATIONS_COUNT';
export const FETCH_NOTIFICATIONS_COUNT_SUCCESS = 'FETCH_NOTIFICATIONS_COUNT_SUCCESS';
export const FETCH_NOTIFICATIONS_COUNT_ERROR = 'FETCH_NOTIFICATIONS_COUNT_ERROR';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

export const MARK_ALL_NOTIFICATIONS_VIEWED = 'MARK_ALL_NOTIFICATIONS_VIEWED';
export const MARK_ALL_NOTIFICATIONS_VIEWED_SUCCESS = 'MARK_ALL_NOTIFICATIONS_VIEWED_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_VIEWED_ERROR = 'MARK_ALL_NOTIFICATIONS_VIEWED_ERROR';

export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const MARK_ALL_NOTIFICATIONS_READ_SUCCESS = 'MARK_ALL_NOTIFICATIONS_READ_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_READ_ERROR = 'MARK_ALL_NOTIFICATIONS_READ_ERROR';

export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_NOTIFICATION_READ_SUCCESS = 'MARK_NOTIFICATION_READ_SUCCESS';
export const MARK_NOTIFICATION_READ_ERROR = 'MARK_NOTIFICATION_READ_ERROR';

export const RECORD_POST_VIEW = 'RECORD_POST_VIEW';
export const RECORD_POST_VIEW_SUCCESS = 'RECORD_POST_VIEW_SUCCESS';
export const RECORD_POST_VIEW_ERROR = 'RECORD_POST_VIEW_ERROR';

export const DEPLOY_CONTRACT = 'DEPLOY_CONTRACT';
export const DEPLOY_CONTRACT_SUCCESS = 'DEPLOY_CONTRACT_SUCCESS';
export const DEPLOY_CONTRACT_ERROR = 'DEPLOY_CONTRACT_ERROR';

export const INIT_CONTRACTS = 'INIT_CONTRACTS';
export const INIT_CONTRACTS_SUCCESS = 'INIT_CONTRACTS_SUCCESS';
export const INIT_CONTRACTS_ERROR = 'INIT_CONTRACTS_ERROR';

export const FETCH_USER_BALANCE = 'FETCH_USER_BALANCE';
export const FETCH_USER_BALANCE_SUCCESS = 'FETCH_USER_BALANCE_SUCCESS';
export const FETCH_USER_BALANCE_ERROR = 'FETCH_USER_BALANCE_ERROR';

export const FETCH_TRANSFERS_HISTORY = 'FETCH_TRANSFERS_HISTORY';
export const FETCH_TRANSFERS_HISTORY_SUCCESS = 'FETCH_TRANSFERS_HISTORY_SUCCESS';
export const FETCH_TRANSFERS_HISTORY_ERROR = 'FETCH_TRANSFERS_HISTORY_ERROR';
export const RESET_TRANSFERS_HISTORY_STATUS = 'RESET_TRANSFERS_HISTORY_STATUS';
export const RESET_BALANCE_STATUS = 'RESET_BALANCE_STATUS';

export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_AUTH_SUCCESS = 'UPDATE_AUTH_SUCCESS';
export const UPDATE_AUTH_ERROR = 'UPDATE_AUTH_ERROR';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';

export const FETCH_WAIT_BLOCK = 'FETCH_WAIT_BLOCK';
export const FETCH_WAIT_BLOCK_SUCCESS = 'FETCH_WAIT_BLOCK_SUCCESS';
export const FETCH_WAIT_BLOCK_ERROR = 'FETCH_WAIT_BLOCK_ERROR';

export const FETCH_WAIT_TRX_CONTENT = 'FETCH_WAIT_TRX_CONTENT';
export const FETCH_WAIT_TRX_CONTENT_SUCCESS = 'FETCH_WAIT_TRX_CONTENT_SUCCESS';
export const FETCH_WAIT_TRX_CONTENT_ERROR = 'FETCH_WAIT_TRX_CONTENT_ERROR';

export const FETCH_LEADERS = 'FETCH_LEADERS';
export const FETCH_LEADERS_SUCCESS = 'FETCH_LEADERS_SUCCESS';
export const FETCH_LEADERS_ERROR = 'FETCH_LEADERS_ERROR';

export const FETCH_SUBSCRIPTIONS = 'FETCH_SUBSCRIPTIONS';
export const FETCH_SUBSCRIPTIONS_SUCCESS = 'FETCH_SUBSCRIPTIONS_SUCCESS';
export const FETCH_SUBSCRIPTIONS_ERROR = 'FETCH_SUBSCRIPTIONS_ERROR';

export const FETCH_SUBSCRIBERS = 'FETCH_SUBSCRIBERS';
export const FETCH_SUBSCRIBERS_SUCCESS = 'FETCH_SUBSCRIBERS_SUCCESS';
export const FETCH_SUBSCRIBERS_ERROR = 'FETCH_SUBSCRIBERS_ERROR';
