export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const VOTE_POST = 'VOTE_POST';
export const VOTE_POST_SUCCESS = 'VOTE_POST_SUCCESS';
export const VOTE_POST_ERROR = 'VOTE_POST_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_COMMENT = 'FETCH_POST_COMMENT';
export const FETCH_POST_COMMENT_SUCCESS = 'FETCH_POST_COMMENT_SUCCESS';
export const FETCH_POST_COMMENT_ERROR = 'FETCH_POST_COMMENT_ERROR';

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const FETCH_FEED_COMMENTS = 'FETCH_FEED_COMMENTS';
export const FETCH_FEED_COMMENTS_SUCCESS = 'FETCH_FEED_COMMENTS_SUCCESS';
export const FETCH_FEED_COMMENTS_ERROR = 'FETCH_FEED_COMMENTS_ERROR';

export const FETCH_POST_COMMENTS_NESTED = 'FETCH_POST_COMMENTS_NESTED';
export const FETCH_POST_COMMENTS_NESTED_SUCCESS = 'FETCH_POST_COMMENTS_NESTED_SUCCESS';
export const FETCH_POST_COMMENTS_NESTED_ERROR = 'FETCH_POST_COMMENTS_NESTED_ERROR';

export const DELETE_COMMENT = 'DELETE_COMMENT';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const UPDATE_UI_MODE = 'UPDATE_UI_MODE';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const GATE_AUTHORIZE_SECRET = 'GATE_AUTHORIZE_SECRET';
export const GATE_AUTHORIZE_SECRET_SUCCESS = 'GATE_AUTHORIZE_SECRET_SUCCESS';
export const GATE_AUTHORIZE_SECRET_ERROR = 'GATE_AUTHORIZE_SECRET_ERROR';

export const GATE_AUTHORIZE = 'GATE_AUTHORIZE';
export const GATE_AUTHORIZE_SUCCESS = 'GATE_AUTHORIZE_SUCCESS';
export const GATE_AUTHORIZE_ERROR = 'GATE_AUTHORIZE_ERROR';

export const SET_SERVER_ACCOUNT_NAME = 'SET_SERVER_ACCOUNT_NAME';
export const SET_SERVER_REFERRAL_ID = 'SET_SERVER_REFERRAL_ID';

export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER';

export const PROVIDE_BW = 'PROVIDE_BW';
export const PROVIDE_BW_SUCCESS = 'PROVIDE_BW_SUCCESS';
export const PROVIDE_BW_ERROR = 'PROVIDE_BW_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

export const FETCH_EMBED = 'FETCH_EMBED';
export const FETCH_EMBED_SUCCESS = 'FETCH_EMBED_SUCCESS';
export const FETCH_EMBED_ERROR = 'FETCH_EMBED_ERROR';

/* for registration */
export const REG_SET_SCREEN_ID = 'REG_SET_SCREEN_ID';
export const REG_SET_PHONE_NUMBER = 'REG_SET_PHONE_NUMBER';
export const REG_SET_FULL_PHONE_NUMBER = 'REG_SET_FULL_PHONE_NUMBER';
export const REG_SET_LOC_DATA = 'REG_SET_LOC_DATA';
export const REG_SET_WISH_USERNAME = 'REG_SET_WISH_USERNAME';
export const REG_SET_USER_ID = 'REG_SET_USER_ID';
export const REG_CLEAR_DATA = 'REG_CLEAR_DATA';
export const REG_SET_LOCAL_STORAGE_DATA = 'REG_SET_LOCAL_STORAGE_DATA';

/* export const FETCH_REG_STATE = 'FETCH_REG_STATE';
export const FETCH_REG_STATE_SUCCESS = 'FETCH_REG_STATE_SUCCESS';
export const FETCH_REG_STATE_ERROR = 'FETCH_REG_STATE_ERROR'; */

export const FETCH_REG_FIRST_STEP = 'FETCH_REG_FIRST_STEP';
export const FETCH_REG_FIRST_STEP_SUCCESS = 'FETCH_REG_FIRST_STEP_SUCCESS';
export const FETCH_REG_FIRST_STEP_ERROR = 'FETCH_REG_FIRST_STEP_ERROR';
export const SET_FIRST_STEP_ERROR = 'SET_FIRST_STEP_ERROR';
export const FIRST_STEP_STOP_LOADER = 'FIRST_STEP_STOP_LOADER';

export const FETCH_REG_VERIFY = 'FETCH_REG_VERIFY';
export const FETCH_REG_VERIFY_SUCCESS = 'FETCH_REG_VERIFY_SUCCESS';
export const FETCH_REG_VERIFY_ERROR = 'FETCH_REG_VERIFY_ERROR';
export const CLEAR_VERIFY_ERROR = 'CLEAR_VERIFY_ERROR';
export const CLEAR_REG_ERRORS = 'CLEAR_REG_ERRORS';

export const FETCH_RESEND_SMS = 'FETCH_RESEND_SMS';
export const FETCH_RESEND_SMS_SUCCESS = 'FETCH_RESEND_SMS_SUCCESS';
export const FETCH_RESEND_SMS_ERROR = 'FETCH_RESEND_SMS_ERROR';

export const FETCH_REG_SET_USER = 'FETCH_REG_SET_USER';
export const FETCH_REG_SET_USER_SUCCESS = 'FETCH_REG_SET_USER_SUCCESS';
export const FETCH_REG_SET_USER_ERROR = 'FETCH_REG_SET_USER_ERROR';

export const START_REG_BLOCK_CHAIN = 'START_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN = 'FETCH_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN_SUCCESS = 'FETCH_REG_BLOCK_CHAIN_SUCCESS';
export const FETCH_REG_BLOCK_CHAIN_ERROR = 'FETCH_REG_BLOCK_CHAIN_ERROR';
export const BLOCK_CHAIN_STOP_LOADER = 'BLOCK_CHAIN_STOP_LOADER';
export const SET_USERS_KEYS = 'SET_USERS_KEYS';

export const FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS = 'FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS';
export const FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS_SUCCESS =
  'FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS_SUCCESS';
export const FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS_ERROR =
  'FETCH_ONBOARDING_COMMUNITY_SUBSCRIPTIONS_ERROR';

/* for actions with users and communities  */
export const SET_POST_VOTE = 'SET_POST_VOTE';
export const SET_COMMENT_VOTE = 'SET_COMMENT_VOTE';

export const PIN = 'PIN';
export const PIN_SUCCESS = 'PIN_SUCCESS';
export const PIN_ERROR = 'PIN_ERROR';

export const UNPIN = 'UNPIN';
export const UNPIN_SUCCESS = 'UNPIN_SUCCESS';
export const UNPIN_ERROR = 'UNPIN_ERROR';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR';

export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_ERROR = 'UNBLOCK_USER_ERROR';

export const VOTE_LEADER = 'VOTE_LEADER';
export const VOTE_LEADER_SUCCESS = 'VOTE_LEADER_SUCCESS';
export const VOTE_LEADER_ERROR = 'VOTE_LEADER_ERROR';

export const UNVOTE_LEADER = 'UNVOTE_LEADER';
export const UNVOTE_LEADER_SUCCESS = 'UNVOTE_LEADER_SUCCESS';
export const UNVOTE_LEADER_ERROR = 'UNVOTE_LEADER_ERROR';

export const TRANSFER_TOKEN = 'TRANSFER_TOKEN';
export const TRANSFER_TOKEN_SUCCESS = 'TRANSFER_TOKEN_SUCCESS';
export const TRANSFER_TOKEN_ERROR = 'TRANSFER_TOKEN_ERROR';

export const FETCH_NOTIFICATIONS_STATUS = 'FETCH_NOTIFICATIONS_STATUS';
export const FETCH_NOTIFICATIONS_STATUS_SUCCESS = 'FETCH_NOTIFICATIONS_STATUS_SUCCESS';
export const FETCH_NOTIFICATIONS_STATUS_ERROR = 'FETCH_NOTIFICATIONS_STATUS_ERROR';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

export const FETCH_TRAY_NOTIFICATIONS = 'FETCH_TRAY_NOTIFICATIONS';
export const FETCH_TRAY_NOTIFICATIONS_SUCCESS = 'FETCH_TRAY_NOTIFICATIONS_SUCCESS';
export const FETCH_TRAY_NOTIFICATIONS_ERROR = 'FETCH_TRAY_NOTIFICATIONS_ERROR';

export const MARK_ALL_NOTIFICATIONS_READ = 'MARK_ALL_NOTIFICATIONS_READ';
export const MARK_ALL_NOTIFICATIONS_READ_SUCCESS = 'MARK_ALL_NOTIFICATIONS_READ_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_READ_ERROR = 'MARK_ALL_NOTIFICATIONS_READ_ERROR';

export const MARK_ALL_NOTIFICATIONS_READ_IN_STORE = 'MARK_ALL_NOTIFICATIONS_READ_IN_STORE';

export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ';
export const MARK_NOTIFICATION_READ_SUCCESS = 'MARK_NOTIFICATION_READ_SUCCESS';
export const MARK_NOTIFICATION_READ_ERROR = 'MARK_NOTIFICATION_READ_ERROR';

export const RECORD_POST_VIEW = 'RECORD_POST_VIEW';
export const RECORD_POST_VIEW_SUCCESS = 'RECORD_POST_VIEW_SUCCESS';
export const RECORD_POST_VIEW_ERROR = 'RECORD_POST_VIEW_ERROR';

export const FETCH_USER_BALANCE = 'FETCH_USER_BALANCE';
export const FETCH_USER_BALANCE_SUCCESS = 'FETCH_USER_BALANCE_SUCCESS';
export const FETCH_USER_BALANCE_ERROR = 'FETCH_USER_BALANCE_ERROR';

export const FETCH_TRANSFERS_HISTORY = 'FETCH_TRANSFERS_HISTORY';
export const FETCH_TRANSFERS_HISTORY_SUCCESS = 'FETCH_TRANSFERS_HISTORY_SUCCESS';
export const FETCH_TRANSFERS_HISTORY_ERROR = 'FETCH_TRANSFERS_HISTORY_ERROR';
export const RESET_TRANSFERS_HISTORY_STATUS = 'RESET_TRANSFERS_HISTORY_STATUS';
export const RESET_BALANCE_STATUS = 'RESET_BALANCE_STATUS';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';

export const FETCH_WAIT_BLOCK = 'FETCH_WAIT_BLOCK';
export const FETCH_WAIT_BLOCK_SUCCESS = 'FETCH_WAIT_BLOCK_SUCCESS';
export const FETCH_WAIT_BLOCK_ERROR = 'FETCH_WAIT_BLOCK_ERROR';

export const FETCH_LEADERS = 'FETCH_LEADERS';
export const FETCH_LEADERS_SUCCESS = 'FETCH_LEADERS_SUCCESS';
export const FETCH_LEADERS_ERROR = 'FETCH_LEADERS_ERROR';

export const FETCH_USER_SUBSCRIPTIONS = 'FETCH_USER_SUBSCRIPTIONS';
export const FETCH_USER_SUBSCRIPTIONS_SUCCESS = 'FETCH_USER_SUBSCRIPTIONS_SUCCESS';
export const FETCH_USER_SUBSCRIPTIONS_ERROR = 'FETCH_USER_SUBSCRIPTIONS_ERROR';

export const FETCH_SUBSCRIBERS = 'FETCH_SUBSCRIBERS';
export const FETCH_SUBSCRIBERS_SUCCESS = 'FETCH_SUBSCRIBERS_SUCCESS';
export const FETCH_SUBSCRIBERS_ERROR = 'FETCH_SUBSCRIBERS_ERROR';

export const OPEN_WALLET = 'OPEN_WALLET';
export const OPEN_WALLET_SUCCESS = 'OPEN_WALLET_SUCCESS';
export const OPEN_WALLET_ERROR = 'OPEN_WALLET_ERROR';

export const CLOSE_WALLET = 'CLOSE_WALLET';
export const CLOSE_WALLET_SUCCESS = 'CLOSE_WALLET_SUCCESS';
export const CLOSE_WALLET_ERROR = 'CLOSE_WALLET_ERROR';

export const TRANSFER_POINT = 'TRANSFER_POINT';
export const TRANSFER_POINT_SUCCESS = 'TRANSFER_POINT_SUCCESS';
export const TRANSFER_POINT_ERROR = 'TRANSFER_POINT_ERROR';

export const FETCH_COMMUNITIES = 'FETCH_COMMUNITIES';
export const FETCH_COMMUNITIES_SUCCESS = 'FETCH_COMMUNITIES_SUCCESS';
export const FETCH_COMMUNITIES_ERROR = 'FETCH_COMMUNITIES_ERROR';

export const FETCH_USER_COMMUNITIES = 'FETCH_USER_COMMUNITIES';
export const FETCH_USER_COMMUNITIES_SUCCESS = 'FETCH_USER_COMMUNITIES_SUCCESS';
export const FETCH_USER_COMMUNITIES_ERROR = 'FETCH_USER_COMMUNITIES_ERROR';

export const FETCH_MY_COMMUNITIES = 'FETCH_MY_COMMUNITIES';
export const FETCH_MY_COMMUNITIES_SUCCESS = 'FETCH_MY_COMMUNITIES_SUCCESS';
export const FETCH_MY_COMMUNITIES_ERROR = 'FETCH_MY_COMMUNITIES_ERROR';

export const FETCH_USERS_BLACKLIST = 'FETCH_USERS_BLACKLIST';
export const FETCH_USERS_BLACKLIST_SUCCESS = 'FETCH_USERS_BLACKLIST_SUCCESS';
export const FETCH_USERS_BLACKLIST_ERROR = 'FETCH_USERS_BLACKLIST_ERROR';

export const FETCH_COMMUNITIES_BLACKLIST = 'FETCH_COMMUNITIES_BLACKLIST';
export const FETCH_COMMUNITIES_BLACKLIST_SUCCESS = 'FETCH_COMMUNITIES_BLACKLIST_SUCCESS';
export const FETCH_COMMUNITIES_BLACKLIST_ERROR = 'FETCH_COMMUNITIES_BLACKLIST_ERROR';

export const FETCH_COMMUNITY = 'FETCH_COMMUNITY';
export const FETCH_COMMUNITY_SUCCESS = 'FETCH_COMMUNITY_SUCCESS';
export const FETCH_COMMUNITY_ERROR = 'FETCH_COMMUNITY_ERROR';

export const SEND_REPORT = 'SEND_REPORT';
export const SEND_REPORT_SUCCESS = 'SEND_REPORT_SUCCESS';
export const SEND_REPORT_ERROR = 'SEND_REPORT_ERROR';

export const JOIN_COMMUNITY = 'JOIN_COMMUNITY';
export const JOIN_COMMUNITY_SUCCESS = 'JOIN_COMMUNITY_SUCCESS';
export const JOIN_COMMUNITY_ERROR = 'JOIN_COMMUNITY_ERROR';

export const LEAVE_COMMUNITY = 'LEAVE_COMMUNITY';
export const LEAVE_COMMUNITY_SUCCESS = 'LEAVE_COMMUNITY_SUCCESS';
export const LEAVE_COMMUNITY_ERROR = 'LEAVE_COMMUNITY_ERROR';

export const BLOCK_COMMUNITY = 'BLOCK_COMMUNITY';
export const BLOCK_COMMUNITY_SUCCESS = 'BLOCK_COMMUNITY_SUCCESS';
export const BLOCK_COMMUNITY_ERROR = 'BLOCK_COMMUNITY_ERROR';

export const UNBLOCK_COMMUNITY = 'UNBLOCK_COMMUNITY';
export const UNBLOCK_COMMUNITY_SUCCESS = 'UNBLOCK_COMMUNITY_SUCCESS';
export const UNBLOCK_COMMUNITY_ERROR = 'UNBLOCK_COMMUNITY_ERROR';

export const FETCH_COMMUNITY_MEMBERS = 'FETCH_COMMUNITY_MEMBERS';
export const FETCH_COMMUNITY_MEMBERS_SUCCESS = 'FETCH_COMMUNITY_MEMBERS_SUCCESS';
export const FETCH_COMMUNITY_MEMBERS_ERROR = 'FETCH_COMMUNITY_MEMBERS_ERROR';

export const FETCH_COMMUNITY_MEMBERS_WIDGET = 'FETCH_COMMUNITY_MEMBERS_WIDGET';
export const FETCH_COMMUNITY_MEMBERS_WIDGET_SUCCESS = 'FETCH_COMMUNITY_MEMBERS_WIDGET_SUCCESS';
export const FETCH_COMMUNITY_MEMBERS_WIDGET_ERROR = 'FETCH_COMMUNITY_MEMBERS_WIDGET_ERROR';

export const FETCH_TRENDING_COMMUNITIES = 'FETCH_TRENDING_COMMUNITIES';
export const FETCH_TRENDING_COMMUNITIES_SUCCESS = 'FETCH_TRENDING_COMMUNITIES_SUCCESS';
export const FETCH_TRENDING_COMMUNITIES_ERROR = 'FETCH_TRENDING_COMMUNITIES_ERROR';

export const FETCH_LEADERS_WIDGET = 'FETCH_LEADERS_WIDGET';
export const FETCH_LEADERS_WIDGET_SUCCESS = 'FETCH_LEADERS_WIDGET_SUCCESS';
export const FETCH_LEADERS_WIDGET_ERROR = 'FETCH_LEADERS_WIDGET_ERROR';

export const OPEN_POST_EDITOR = 'OPEN_POST_EDITOR';
export const CLOSE_POST_EDITOR = 'CLOSE_POST_EDITOR';

export const BECOME_LEADER = 'BECOME_LEADER';
export const BECOME_LEADER_SUCCESS = 'BECOME_LEADER_SUCCESS';
export const BECOME_LEADER_ERROR = 'BECOME_LEADER_ERROR';

export const STOP_LEADER = 'STOP_LEADER';
export const STOP_LEADER_SUCCESS = 'STOP_LEADER_SUCCESS';
export const STOP_LEADER_ERROR = 'STOP_LEADER_ERROR';

export const CLEAR_LEADER_VOTES = 'CLEAR_LEADER_VOTES';
export const CLEAR_LEADER_VOTES_SUCCESS = 'CLEAR_LEADER_VOTES_SUCCESS';
export const CLEAR_LEADER_VOTES_ERROR = 'CLEAR_LEADER_VOTES_ERROR';

export const UNREG_LEADER = 'UNREG_LEADER';
export const UNREG_LEADER_SUCCESS = 'UNREG_LEADER_SUCCESS';
export const UNREG_LEADER_ERROR = 'UNREG_LEADER_ERROR';

export const FETCH_PROPOSALS = 'FETCH_PROPOSALS';
export const FETCH_PROPOSALS_SUCCESS = 'FETCH_PROPOSALS_SUCCESS';
export const FETCH_PROPOSALS_ERROR = 'FETCH_PROPOSALS_ERROR';

export const FETCH_PROPOSAL = 'FETCH_PROPOSAL';
export const FETCH_PROPOSAL_SUCCESS = 'FETCH_PROPOSAL_SUCCESS';
export const FETCH_PROPOSAL_ERROR = 'FETCH_PROPOSAL_ERROR';

export const APPROVE_PROPOSAL = 'APPROVE_PROPOSAL';
export const APPROVE_PROPOSAL_SUCCESS = 'APPROVE_PROPOSAL_SUCCESS';
export const APPROVE_PROPOSAL_ERROR = 'APPROVE_PROPOSAL_ERROR';

export const CANCEL_PROPOSAL_APPROVE = 'CANCEL_PROPOSAL_APPROVE';
export const CANCEL_PROPOSAL_APPROVE_SUCCESS = 'CANCEL_PROPOSAL_APPROVE_SUCCESS';
export const CANCEL_PROPOSAL_APPROVE_ERROR = 'CANCEL_PROPOSAL_APPROVE_ERROR';

export const CANCEL_PROPOSAL = 'CANCEL_PROPOSAL';
export const CANCEL_PROPOSAL_SUCCESS = 'CANCEL_PROPOSAL_SUCCESS';
export const CANCEL_PROPOSAL_ERROR = 'CANCEL_PROPOSAL_ERROR';

export const FETCH_LEADER_COMMUNITIES = 'FETCH_LEADER_COMMUNITIES';
export const FETCH_LEADER_COMMUNITIES_SUCCESS = 'FETCH_LEADER_COMMUNITIES_SUCCESS';
export const FETCH_LEADER_COMMUNITIES_ERROR = 'FETCH_LEADER_COMMUNITIES_ERROR';

export const FETCH_REPORTS_LIST = 'FETCH_REPORTS_LIST';
export const FETCH_REPORTS_LIST_SUCCESS = 'FETCH_REPORTS_LIST_SUCCESS';
export const FETCH_REPORTS_LIST_ERROR = 'FETCH_REPORTS_LIST_ERROR';

export const FETCH_REPORTS_ENTITY = 'FETCH_REPORTS_ENTITY';
export const FETCH_REPORTS_ENTITY_SUCCESS = 'FETCH_REPORTS_ENTITY_SUCCESS';
export const FETCH_REPORTS_ENTITY_ERROR = 'FETCH_REPORTS_ENTITY_ERROR';

export const FETCH_MANAGEMENT_COMMUNITIES = 'FETCH_MANAGEMENT_COMMUNITIES';
export const FETCH_MANAGEMENT_COMMUNITIES_SUCCESS = 'FETCH_MANAGEMENT_COMMUNITIES_SUCCESS';
export const FETCH_MANAGEMENT_COMMUNITIES_ERROR = 'FETCH_MANAGEMENT_COMMUNITIES_ERROR';

// Leader board
export const SELECT_COMMUNITY = 'SELECT_COMMUNITY';
export const CLEAR_COMMUNITY_FILTER = 'CLEAR_COMMUNITY_FILTER';
export const SET_SELECTED_COMMUNITIES = 'SET_SELECTED_COMMUNITIES';

export const EXEC_PROPOSAL = 'EXEC_PROPOSAL';
export const EXEC_PROPOSAL_SUCCESS = 'EXEC_PROPOSAL_SUCCESS';
export const EXEC_PROPOSAL_ERROR = 'EXEC_PROPOSAL_ERROR';

export const SET_EDITOR_STATE = 'SET_EDITOR_STATE';

// wallet
export const SHOW_POINT_INFO = 'SHOW_POINT_INFO';

export const FETCH_POINT_HISTORY = 'FETCH_POINT_HISTORY';
export const FETCH_POINT_HISTORY_SUCCESS = 'FETCH_POINT_HISTORY_SUCCESS';
export const FETCH_POINT_HISTORY_ERROR = 'FETCH_POINT_HISTORY_ERROR';

export const FETCH_EXCHANGE_CURRENCIES = 'FETCH_EXCHANGE_CURRENCIES';
export const FETCH_EXCHANGE_CURRENCIES_SUCCESS = 'FETCH_EXCHANGE_CURRENCIES_SUCCESS';
export const FETCH_EXCHANGE_CURRENCIES_ERROR = 'FETCH_EXCHANGE_CURRENCIES_ERROR';

export const FETCH_EXCHANGE_CURRENCIES_FULL = 'FETCH_EXCHANGE_CURRENCIES_FULL';
export const FETCH_EXCHANGE_CURRENCIES_FULL_SUCCESS = 'FETCH_EXCHANGE_CURRENCIES_FULL_SUCCESS';
export const FETCH_EXCHANGE_CURRENCIES_FULL_ERROR = 'FETCH_EXCHANGE_CURRENCIES_FULL_ERROR';

export const SET_BAN_POST_PROPOSAL = 'SET_BAN_POST_PROPOSAL';

export const REMOVE_REPORT = 'REMOVE_REPORT';
