export const SHOW_MODAL_CONFIRM = 'SHOW_MODAL_CONFIRM';
export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const SHOW_MODAL_SIGNUP = 'SHOW_MODAL_SIGNUP';
export const SHOW_MODAL_PROFILE_ABOUT_EDIT = 'SHOW_MODAL_PROFILE_ABOUT_EDIT';
export const SHOW_MODAL_AVATAR_EDIT = 'SHOW_MODAL_AVATAR_EDIT';
export const SHOW_MODAL_SEND_POINTS = 'SHOW_MODAL_SEND_POINTS';
export const SHOW_MODAL_CONVERT_POINTS = 'SHOW_MODAL_CONVERT_POINTS';
export const SHOW_MODAL_POST = 'SHOW_MODAL_POST';
export const SHOW_MODAL_POST_EDIT = 'SHOW_MODAL_POST_EDIT';
export const SHOW_MODAL_RULE_EDIT = 'SHOW_MODAL_RULE_EDIT';
export const SHOW_MODAL_DESCRIPTION_EDIT = 'SHOW_MODAL_DESCRIPTION_EDIT';
export const SHOW_MODAL_NEW_POST_EDITOR = 'SHOW_MODAL_NEW_POST_EDITOR';
export const SHOW_MODAL_SET_CONTRACTS_KEYS = 'SHOW_MODAL_SET_CONTRACTS_KEYS';
export const SHOW_MODAL_COMMUNITY_INIT_STATUS = 'SHOW_MODAL_COMMUNITY_INIT_STATUS';
export const SHOW_MODAL_BECOME_LEADER = 'SHOW_MODAL_BECOME_LEADER';
export const SHOW_MODAL_SHARE = 'SHOW_MODAL_SHARE';

export const OPENED_FROM_LOGIN = 'OPENED_FROM_LOGIN';
